name: ServerTransfers
version: 1.0
api-version: 1.21
main: com.authorinthedark.servertransfers.TransferPlugin
commands:
  transfer:
    description: Send yourself to another world
    usage: /transfer <server name>
